
micronaut:
  application:
    name: bookshopService
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/bookshop-db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
flyway:
  datasources:
    default:
      enabled: true
